;;;; src/model.lisp
(in-package #:cl-toml-kit)

(define-toml-model toml-string-value ((value "" string)))
(define-toml-model toml-integer-value ((value 0 integer)))
(define-toml-model toml-float-value ((value 0.0 float)))
(define-toml-model toml-boolean-value ((value nil boolean)))
(define-toml-model toml-table ((entries nil list)))
(define-toml-model toml-array ((elements nil list)))
(define-toml-model toml-document ((entries nil list)))

(defun string-value-p (value) (toml-string-value-p value))
(defun string-value (value) (toml-string-value-value value))
(defun integer-value-p (value) (toml-integer-value-p value))
(defun integer-value (value) (toml-integer-value-value value))
(defun float-value-p (value) (toml-float-value-p value))
(defun float-value (value) (toml-float-value-value value))
(defun boolean-value-p (value) (toml-boolean-value-p value))
(defun boolean-value (value) (toml-boolean-value-value value))

(defun make-string-value (value)
  (check-type value string) (make-toml-string-value :value value))
(defun make-integer-value (value)
  (check-type value integer) (make-toml-integer-value :value value))
(defun make-float-value (value)
  (check-type value float) (make-toml-float-value :value value))
(defun make-boolean-value (value)
  (check-type value boolean) (make-toml-boolean-value :value value))
(defun make-array-value (&optional elements)
  (make-toml-array :elements (copy-list elements)))
(defun make-table-value (&optional entries)
  (make-toml-table :entries (copy-list entries)))
(defun array-elements (value)
  (check-type value toml-array) (toml-array-elements value))
(defun table-entries (value)
  (check-type value toml-table) (toml-table-entries value))
(defun toml-key-p (value)
  (or (stringp value) (symbolp value) (and (integerp value) (>= value 0))))

(defun %find-date-predicate (name)
  (let* ((package (find-package "CL-DATE-KIT"))
         (symbol (and package (find-symbol name package))))
    (and symbol (fboundp symbol) symbol)))
(defun %date-kind-p (value names)
  (some (lambda (name)
          (let ((predicate (%find-date-predicate name)))
            (and predicate (funcall predicate value)))) names))
(defun toml-date-p (value) (%date-kind-p value '("LOCAL-DATE-P")))
(defun toml-time-p (value)
  (%date-kind-p value '("LOCAL-TIME-P" "OFFSET-TIME-P")))
(defun toml-offset-date-time-p (value)
  (%date-kind-p value '("OFFSET-DATE-TIME-P")))
(defun toml-zoned-date-time-p (value)
  (%date-kind-p value '("ZONED-DATE-TIME-P")))
(defun toml-date-time-p (value)
  (%date-kind-p value '("LOCAL-DATE-TIME-P" "OFFSET-DATE-TIME-P"
                        "ZONED-DATE-TIME-P")))

(defun toml-value-p (value)
  (or (toml-string-value-p value) (toml-integer-value-p value)
      (toml-float-value-p value) (toml-boolean-value-p value)
      (toml-table-p value) (toml-array-p value) (toml-date-time-p value)
      (toml-date-p value) (toml-time-p value)))
(defun toml-value-kind (value)
  (cond ((toml-table-p value) :table) ((toml-array-p value) :array)
        ((toml-string-value-p value) :string)
        ((toml-integer-value-p value) :integer)
        ((toml-float-value-p value) :float)
        ((toml-boolean-value-p value) :boolean)
        ((toml-date-time-p value) :date-time) ((toml-date-p value) :date)
        ((toml-time-p value) :time) (t nil)))
(defun toml-value-kind-p (value kind)
  (eq (toml-value-kind value) kind))

(defun toml-table-get (table key &optional default)
  (check-type table toml-table)
  (let ((entry (assoc key (toml-table-entries table) :test #'equal)))
    (if entry (cdr entry) default)))
(defun table-value (table key &optional default)
  (toml-table-get table key default))
(defun toml-table-set (table key value)
  (check-type table toml-table)
  (unless (toml-key-p key)
    (error 'toml-encoding-error :message "Invalid TOML key" :path (list key)))
  (unless (toml-value-p value)
    (error 'toml-encoding-error :message "Not a TOML value" :path (list key)))
  (let ((entry (assoc key (toml-table-entries table) :test #'equal)))
    (if entry (setf (cdr entry) value)
        (setf (toml-table-entries table)
              (nconc (toml-table-entries table) (list (cons key value))))))
  table)
(defun toml-get (table key &optional default)
  (toml-table-get table key default))
(defun toml-set (table key value)
  (toml-table-set table key value))
(defun toml-array-push (array value)
  (check-type array toml-array)
  (unless (toml-value-p value)
    (error 'toml-encoding-error :message "Not a TOML value"))
  (setf (toml-array-elements array)
        (nconc (toml-array-elements array) (list value)))
  array)
