;;;; src/reader-values.lisp
(in-package #:cl-toml-kit)

(defun %value-error (state position expected)
  (%error-at state position expected))

(defun %buffer-reset (state)
  (setf (fill-pointer (toml-reader-state-buffer state)) 0))

(defun %buffer-char (state char)
  (vector-push-extend char (toml-reader-state-buffer state)))

(defun %finish-buffer (state)
  (coerce (toml-reader-state-buffer state) 'simple-string))

(defun %hex-digit (char)
  (digit-char-p char 16))

(defun %read-escape (state position)
  (let* ((source (toml-reader-state-source state))
         (char (%source-char state (1+ position)))
         (index (position char +toml-escape-letters+ :test #'char=)))
    (cond
      (index (values (aref +toml-escape-table+ index) (+ position 2)))
      ((member char '(#\x #\u #\U))
       (let ((count (case char (#\x 2) (#\u 4) (otherwise 8))) (value 0))
         (loop for i below count
               for digit = (%hex-digit (%source-char state (+ position 2 i)))
               do (unless digit (%value-error state (+ position 2 i) "hex digit"))
                  (setf value (+ (* value 16) digit)))
         (unless (or (<= value #xD7FF) (>= value #xE000))
           (%value-error state position "Unicode scalar value"))
         (values (or (code-char value) (%value-error state position "Unicode scalar value"))
                 (+ position 2 count))))
      (t (%value-error state position "valid escape sequence")))))

(defun %read-string-at (state position quote)
  (let* ((source (toml-reader-state-source state))
         (triple (and (char= (%source-char state (1+ position)) quote)
                      (char= (%source-char state (+ position 2)) quote)))
         (index (+ position (if triple 3 1))))
    (%buffer-reset state)
    (when (and triple (member (%source-char state index) '(#\Newline #\Return)))
      (%advance-to state (1+ index))
      (setf index (toml-reader-state-position state)))
    (loop
      (when (>= index (toml-reader-state-length state))
        (%value-error state index "closing string delimiter"))
      (let ((char (%source-char state index)))
        (cond
          ((and triple (char= char quote)
                (char= (%source-char state (1+ index)) quote)
                (char= (%source-char state (+ index 2)) quote))
           (return (values (%finish-buffer state) (+ index 3))))
          ((and (not triple) (char= char quote))
           (return (values (%finish-buffer state) (1+ index))))
          ((and (char= quote #\") (char= char #\\))
           (if (and triple (member (%source-char state (1+ index)) '(#\Newline #\Return)))
               (progn
                 (incf index)
                 (when (and (char= (%source-char state index) #\Return)
                            (char= (%source-char state (1+ index)) #\Newline))
                   (incf index))
                 (loop while (%space-char-p (%source-char state index)) do (incf index))
                 (when (member (%source-char state index) '(#\Newline #\Return))
                   (incf index)))
               (multiple-value-bind (value next) (%read-escape state index)
                 (%buffer-char state value)
                 (setf index next))))
          ((and (not triple) (member char '(#\Newline #\Return)))
           (%value-error state index "single-line string"))
          ((and (%control-char-p char) (not (char= char #\Tab)))
           (%value-error state index "printable string character"))
          ((and (char= quote #\') (char= char #\Return))
           (%value-error state index "literal string character"))
          (t (%buffer-char state char) (incf index)))))))

(defun %integer-range-ok-p (number)
  (<= -9223372036854775808 number 9223372036854775807))

(defun %digit-value (char base)
  (digit-char-p char base))

(defun %parse-integer-range (state start end)
  (let ((index start) (negative nil) (base 10) (value 0) (digits 0)
        (previous-digit nil) (leading-zero nil))
    (when (member (%source-char state index) '(#\+ #\-))
      (setf negative (char= (%source-char state index) #\-))
      (incf index))
    (when (and (= (+ index 1) end) (char= (%source-char state index) #\0))
      (return-from %parse-integer-range 0))
    (when (and (< (+ index 1) end) (char= (%source-char state index) #\0)
               (member (char-downcase (%source-char state (1+ index))) '(#\x #\o #\b)))
      (setf base (case (char-downcase (%source-char state (1+ index)))
                   (#\x 16) (#\o 8) (otherwise 2)))
      (incf index 2))
    (loop while (< index end)
          for char = (%source-char state index)
          do (progn
               (if (char= char #\_)
                   (progn
                     (unless previous-digit
                       (%value-error state index "digit between underscores"))
                     (setf previous-digit nil))
                   (let ((digit (%digit-value char base)))
                     (unless digit (%value-error state index "integer digit"))
                     (when (and (= base 10) (zerop digits) (zerop digit))
                       (setf leading-zero t))
                     (when (and leading-zero (= digits 1))
                       (%value-error state index "no leading zero"))
                     (setf value (+ (* value base) digit)
                           previous-digit t)
                     (incf digits)))
               (incf index)))
    (unless (and (> digits 0) previous-digit)
      (%value-error state end "integer digit"))
    (setf value (if negative (- value) value))
    (unless (%integer-range-ok-p value) (%value-error state start "signed 64-bit integer"))
    value))

(defun %parse-float-range (state start end)
  (let ((index start) (negative nil) (mantissa 0) (fraction 0) (digits 0)
        (exponent 0) (exp-negative nil) (seen-dot nil) (seen-exp nil)
        (previous-digit nil))
    (when (member (%source-char state index) '(#\+ #\-))
      (setf negative (char= (%source-char state index) #\-)) (incf index))
    (loop while (< index end)
          for char = (%source-char state index)
          do (progn
               (cond
                 ((and (not seen-dot) (not seen-exp) (char= char #\.))
                  (unless previous-digit (%value-error state index "fraction digit"))
                  (setf seen-dot t previous-digit nil))
                 ((and (not seen-exp) (member char '(#\e #\E)))
                  (unless previous-digit (%value-error state index "exponent digit"))
                  (setf seen-exp t previous-digit nil)
                  (incf index)
                  (when (member (%source-char state index) '(#\+ #\-))
                    (setf exp-negative (char= (%source-char state index) #\-))
                    (incf index))
                  (loop while (< index end)
                        for digit = (%digit-value (%source-char state index) 10)
                        do (unless digit (%value-error state index "exponent digit"))
                           (setf exponent (+ (* exponent 10) digit)
                                 previous-digit t)
                           (incf index))
                  (unless previous-digit (%value-error state index "exponent digit"))
                  (return))
                 ((char= char #\_)
                  (unless previous-digit
                    (%value-error state index "digit between underscores"))
                  (setf previous-digit nil))
                 (t
                  (let ((digit (%digit-value char 10)))
                    (unless digit (%value-error state index "float digit"))
                    (setf mantissa (+ (* mantissa 10) digit)
                          previous-digit t)
                    (when seen-dot (incf fraction)))))
               (incf index)))
    (unless previous-digit (%value-error state end "float digit"))
    (let ((power (- (if exp-negative (- exponent) exponent) fraction)))
      (when negative (setf mantissa (- mantissa)))
      (cond ((and (> (abs power) 400) (zerop mantissa)) 0.0d0)
            ((> power 400) (if (minusp mantissa)
                               sb-ext:double-float-negative-infinity
                               sb-ext:double-float-positive-infinity))
            ((< power -400) (if (minusp mantissa) -0.0d0 0.0d0))
            (t (coerce (* mantissa (expt 10 power)) 'double-float))))))

(defun %parse-date-value (state start end)
  (let ((text (subseq (toml-reader-state-source state) start end)))
    (handler-case
        (cond
          ((or (find #\z text :test #'char-equal) (find #\+ text :start 10)
               (and (> (length text) 10) (find #\- text :start 10)))
           (cl-date-kit:parse-offset-date-time text :profile :rfc3339))
          ((and (find #\- text :test #'char=) (find #\: text :test #'char=))
           (cl-date-kit:parse-local-date-time text :profile :rfc3339))
          ((find #\- text :test #'char=) (cl-date-kit:parse-local-date text))
          (t (cl-date-kit:parse-local-time text :profile :rfc3339)))
      (cl-date-kit:cl-date-kit-error ()
        (%value-error state start "valid date or time")))))

(define-toml-rule toml-read-value (state position)
  (let* ((source (toml-reader-state-source state)) (char (%source-char state position)))
    (cond
      ((member char '(#\" #\'))
       (multiple-value-bind (value next) (%read-string-at state position char)
         (funcall continuation value next)))
      ((eql char #\[) (toml-read-array state position continuation))
      ((eql char #\{) (toml-read-inline-table state position continuation))
      (t
       (let* ((end (%scan-value-end state position))
              (text (subseq source position end))
              (value (cond ((string= text "true") t)
                           ((string= text "false") +toml-false+)
                           ((or (find #\- text :test #'char=)
                                (and (find #\: text :test #'char=)
                                     (> (length text) 2)))
                            (%parse-date-value state position end))
                           ((find #\. text :test #'char=) (%parse-float-range state position end))
                           ((find #\e text :test #'char-equal) (%parse-float-range state position end))
                           ((string= text "inf") sb-ext:double-float-positive-infinity)
                           ((string= text "+inf") sb-ext:double-float-positive-infinity)
                           ((string= text "-inf") sb-ext:double-float-negative-infinity)
                           ((member text '("nan" "+nan" "-nan") :test #'string=)
                            (let ((zero 0.0d0)) (/ zero zero)))
                           (t (%parse-integer-range state position end)))))
         (funcall continuation value end))))))

(define-toml-rule toml-read-array (state position)
  (let ((index (1+ position)) (values '()))
    (loop
      (setf (toml-reader-state-position state) index)
      (%skip-space-and-comments state)
      (setf index (toml-reader-state-position state))
      (when (member (%source-char state index) '(#\Newline #\Return))
        (%skip-line-ending state) (setf index (toml-reader-state-position state)))
      (when (eql (%source-char state index) #\])
        (return (funcall continuation (coerce (nreverse values) 'simple-vector)
                          (1+ index))))
      (toml-read-value state index
                       (lambda (value next)
                         (push value values)
                         (setf index next)
                         (setf (toml-reader-state-position state) next)
                         (%skip-space-and-comments state)
                         (setf index (toml-reader-state-position state))
                         (when (eql (%source-char state index) #\,)
                           (incf index))
                         (setf (toml-reader-state-position state) index)
                         (when (eql (%source-char state index) #\])
                           nil))))))

(define-toml-rule toml-read-inline-table (state position)
  (let ((table (make-hash-table :test #'equal)) (index (1+ position)))
    (loop
      (%skip-space-and-comments state) (setf index (toml-reader-state-position state))
      (when (eql (%source-char state index) #\})
        (setf (gethash table (toml-reader-state-table-states state)) :inline)
        (return (funcall continuation table (1+ index))))
      (multiple-value-bind (keys next) (%read-key-path state index)
        (setf index next) (%skip-space-and-comments state)
        (unless (eql (%source-char state index) #\=)
          (%value-error state index "="))
        (incf index) (%skip-space-and-comments state)
        (toml-read-value state index
                         (lambda (value value-end)
                           (when (gethash (car (last keys)) table)
                             (%value-error state value-end "unique inline key"))
                           (setf (gethash (car (last keys)) table) value)
                           (setf index value-end
                                 (toml-reader-state-position state) value-end)
                           (%skip-space-and-comments state)
                           (when (eql (%source-char state index) #\,) (incf index))))))))
