;;;; src/reader-values.lisp
(in-package #:cl-toml-kit)

(defun %buffer-reset (state)
  (setf (fill-pointer (toml-reader-state-buffer state)) 0))

(defun %buffer-char (state char)
  (vector-push-extend char (toml-reader-state-buffer state)))

(defun %finish-buffer (state)
  (coerce (toml-reader-state-buffer state) 'simple-string))

(defun %skip-inline-space (state)
  (loop
    (%skip-space-and-comments state)
    (if (member (%source-char state (toml-reader-state-position state))
                '(#\Newline #\Return))
        (%skip-line-ending state)
        (return))))

(defun %hex-digit (char)
  (digit-char-p char 16))

(defun %read-escape (state position)
  (let* ((char (%source-char state (1+ position)))
         (index (position char +toml-escape-letters+ :test #'char=)))
    (cond
      (index (values (aref +toml-escape-table+ index) (+ position 2)))
      ((member char '(#\x #\u #\U))
       (let ((count (case char (#\x 2) (#\u 4) (otherwise 8))) (value 0))
         (loop for i below count
               for digit = (%hex-digit (%source-char state (+ position 2 i)))
               do (unless digit (%error-at state (+ position 2 i) "hex digit"))
                  (setf value (+ (* value 16) digit)))
         (unless (and (<= value #x10FFFF)
                      (or (<= value #xD7FF) (>= value #xE000)))
           (%error-at state position "Unicode scalar value"))
         (values (or (code-char value) (%error-at state position "Unicode scalar value"))
                 (+ position 2 count))))
      (t (%error-at state position "valid escape sequence")))))

(defun %read-simple-string-at (state position quote)
  (let ((source (toml-reader-state-source state))
        (index (1+ position))
        (length (toml-reader-state-length state)))
    (loop while (< index length)
          for char = (char source index)
          do (cond
               ((char= char quote)
                (return (values (subseq source (1+ position) index)
                                (1+ index) t)))
               ((or (and (char= quote #\") (char= char #\\))
                    (member char '(#\Newline #\Return))
                    (and (%control-char-p char) (not (char= char #\Tab))))
                (return (values nil nil nil)))
               (t (incf index)))
          finally (return (values nil nil nil)))))

(defun %read-string-at (state position quote)
  (let* ((triple (and (char= (%source-char state (1+ position)) quote)
                      (char= (%source-char state (+ position 2)) quote)))
         (index (+ position (if triple 3 1))))
    (unless triple
      (multiple-value-bind (value next found)
          (%read-simple-string-at state position quote)
        (when found
          (return-from %read-string-at (values value next)))))
    (%buffer-reset state)
    (when (and triple (member (%source-char state index) '(#\Newline #\Return)))
      (%advance-to state (1+ index))
      (setf index (toml-reader-state-position state)))
    (loop
      (when (>= index (toml-reader-state-length state))
        (%error-at state index "closing string delimiter"))
      (let ((char (%source-char state index)))
        (cond
          ((and triple (char= char quote)
                (char= (%source-char state (1+ index)) quote)
                (char= (%source-char state (+ index 2)) quote))
           (let ((count 3))
             (loop while (eql (%source-char state (+ index count)) quote)
                   do (incf count))
             (when (> count 5)
               (%error-at state index "multiline string delimiter"))
             (dotimes (ignored (- count 3))
               (declare (ignore ignored))
               (%buffer-char state quote))
             (return (values (%finish-buffer state) (+ index count)))))
          ((and (not triple) (char= char quote))
           (return (values (%finish-buffer state) (1+ index))))
          ((and (char= quote #\") (char= char #\\))
           (if triple
               (let ((continuation (1+ index)))
                 (loop while (%space-char-p (%source-char state continuation))
                       do (incf continuation))
                 (if (member (%source-char state continuation) '(#\Newline #\Return))
                     (progn
                       (setf (toml-reader-state-position state) continuation)
                       (%skip-line-ending state)
                       (setf index (toml-reader-state-position state))
                       (loop
                         (loop while (%space-char-p (%source-char state index)) do (incf index))
                         (if (member (%source-char state index) '(#\Newline #\Return))
                             (progn
                               (setf (toml-reader-state-position state) index)
                               (%skip-line-ending state)
                               (setf index (toml-reader-state-position state)))
                             (return))))
                     (multiple-value-bind (value next) (%read-escape state index)
                       (%buffer-char state value)
                       (setf index next))))
               (multiple-value-bind (value next) (%read-escape state index)
                 (%buffer-char state value)
                 (setf index next))))
          ((and (not triple) (member char '(#\Newline #\Return)))
           (%error-at state index "single-line string"))
          ((and (%control-char-p char) (not (char= char #\Tab)) (not triple))
           (%error-at state index "printable string character"))
          ((and (char= quote #\') (char= char #\Return))
           (%error-at state index "literal string character"))
          (t (%buffer-char state char) (incf index)))))))

(defun %integer-range-ok-p (number)
  (<= -9223372036854775808 number 9223372036854775807))

(defun %digit-value (char base)
  (digit-char-p char base))

(defun %parse-integer-range (state start end)
  (let ((index start) (negative nil) (signed nil) (base 10) (value 0) (digits 0)
        (previous-digit nil) (leading-zero nil))
    (when (member (%source-char state index) '(#\+ #\-))
      (setf negative (char= (%source-char state index) #\-))
      (setf signed t)
      (incf index))
    (when (and (= (+ index 1) end) (char= (%source-char state index) #\0))
      (return-from %parse-integer-range 0))
    (when (and (< (+ index 1) end) (char= (%source-char state index) #\0)
               (member (%source-char state (1+ index)) '(#\x #\o #\b)))
      (when signed (%error-at state start "unsigned prefixed integer"))
      (setf base (case (%source-char state (1+ index))
                   (#\x 16) (#\o 8) (otherwise 2)))
      (incf index 2))
    (loop while (< index end)
          for char = (%source-char state index)
          do (progn
               (if (char= char #\_)
                   (progn
                     (unless previous-digit
                       (%error-at state index "digit between underscores"))
                     (setf previous-digit nil))
                   (let ((digit (%digit-value char base)))
                     (unless digit (%error-at state index "integer digit"))
                     (when (and (= base 10) (zerop digits) (zerop digit))
                       (setf leading-zero t))
                     (when (and leading-zero (= digits 1))
                       (%error-at state index "no leading zero"))
                     (setf value (+ (* value base) digit)
                           previous-digit t)
                     (incf digits)))
               (incf index)))
    (unless (and (> digits 0) previous-digit)
      (%error-at state end "integer digit"))
    (setf value (if negative (- value) value))
    (unless (%integer-range-ok-p value) (%error-at state start "signed 64-bit integer"))
    value))

(defun %parse-float-range (state start end)
  (let ((index start) (negative nil) (mantissa 0) (fraction 0)
        (exponent 0) (exp-negative nil) (seen-dot nil) (seen-exp nil)
        (previous-digit nil))
    (when (member (%source-char state index) '(#\+ #\-))
      (setf negative (char= (%source-char state index) #\-)) (incf index))
    (when (and (char= (%source-char state index) #\0)
               (< (1+ index) end)
               (or (%decimal-char-p (%source-char state (1+ index)))
                   (char= (%source-char state (1+ index)) #\_)))
      (%error-at state (1+ index) "no leading zero"))
    (loop while (< index end)
          for char = (%source-char state index)
          do (progn
               (cond
                 ((and (not seen-dot) (not seen-exp) (char= char #\.))
                  (unless previous-digit (%error-at state index "fraction digit"))
                  (setf seen-dot t previous-digit nil))
                 ((and (not seen-exp) (member char '(#\e #\E)))
                  (unless previous-digit (%error-at state index "exponent digit"))
                  (setf seen-exp t previous-digit nil)
                  (incf index)
                  (when (member (%source-char state index) '(#\+ #\-))
                    (setf exp-negative (char= (%source-char state index) #\-))
                    (incf index))
                  (loop while (< index end)
                        for char = (%source-char state index)
                        do (if (char= char #\_)
                               (progn
                                 (unless previous-digit
                                   (%error-at state index "digit between underscores"))
                                 (setf previous-digit nil))
                               (let ((digit (%digit-value char 10)))
                                 (unless digit (%error-at state index "exponent digit"))
                                 (setf exponent (+ (* exponent 10) digit)
                                       previous-digit t)))
                           (incf index))
                  (unless previous-digit (%error-at state index "exponent digit"))
                  (return))
                 ((char= char #\_)
                  (unless previous-digit
                    (%error-at state index "digit between underscores"))
                  (setf previous-digit nil))
                 (t
                  (let ((digit (%digit-value char 10)))
                    (unless digit (%error-at state index "float digit"))
                    (setf mantissa (+ (* mantissa 10) digit)
                          previous-digit t)
                    (when seen-dot (incf fraction)))))
               (incf index)))
    (unless previous-digit (%error-at state end "float digit"))
    (let ((power (- (if exp-negative (- exponent) exponent) fraction)))
      (when negative (setf mantissa (- mantissa)))
      (handler-case
          (let ((value (coerce (* mantissa (expt 10 power)) 'double-float)))
            (when (and (not (zerop mantissa)) (zerop value))
              (%error-at state start "representable finite floating-point value"))
            value)
        (floating-point-overflow ()
          (%error-at state start "representable finite floating-point value"))))))

(defun %date-time-offset-p (text)
  (let ((index 16)
        (length (length text)))
    (when (and (> length index)
               (member (char text 10) '(#\T #\t #\ )))
      (when (char= (char text index) #\:)
        (incf index 3))
      (when (and (< index length) (char= (char text index) #\.))
        (incf index)
        (loop while (and (< index length)
                         (digit-char-p (char text index)))
              do (incf index)))
      (and (< index length)
           (member (char text index) '(#\z #\Z #\+ #\-))))))

(defun %parse-date-value (state start end)
  (let ((text (subseq (toml-reader-state-source state) start end)))
    (handler-case
        (cond
          ((and (> (length text) 10)
                (member (char text 10) '(#\T #\t #\ ))
                (%date-time-offset-p text))
           (cl-date-kit:parse-offset-date-time text :profile :rfc3339))
          ((and (> (length text) 10)
                (member (char text 10) '(#\T #\t #\ )))
           (cl-date-kit:parse-local-date-time text :profile :rfc3339))
          ((find #\- text :test #'char=) (cl-date-kit:parse-local-date text))
          (t (cl-date-kit:parse-local-time text :profile :rfc3339)))
      (cl-date-kit:cl-date-kit-error ()
        (%error-at state start "valid date or time")))))

(defun %token-equal-p (source start end token)
  (and (= (- end start) (length token))
       (loop for index below (length token)
             always (char= (char source (+ start index)) (char token index)))))

(defun %date-shaped-p (source start end)
  (or (and (>= (- end start) 10)
           (loop for index below 4
                 always (%decimal-char-p (char source (+ start index))))
           (char= (char source (+ start 4)) #\-))
      (and (>= (- end start) 5)
           (%decimal-char-p (char source start))
           (%decimal-char-p (char source (1+ start)))
           (char= (char source (+ start 2)) #\:))))

(defun %float-token-p (source start end)
  (let ((prefix (and (< (+ start 1) end)
                     (char= (char source start) #\0)
                     (member (char-downcase (char source (1+ start)))
                             '(#\x #\o #\b)))))
    (and (not prefix)
         (or (loop for index from start below end
                   thereis (char= (char source index) #\.))
             (loop for index from start below end
                   thereis (member (char source index) '(#\e #\E)))))))

(defparameter +toml-nan+
  (let ((zero 0.0d0))
    (sb-int:with-float-traps-masked (:invalid)
      (/ zero zero))))

(define-toml-rule toml-read-value (state position)
  (let* ((source (toml-reader-state-source state)) (char (%source-char state position)))
    (cond
      ((member char '(#\" #\'))
       (multiple-value-bind (value next) (%read-string-at state position char)
         (funcall continuation value next)))
      ((eql char #\[) (toml-read-array state position continuation))
      ((eql char #\{) (toml-read-inline-table state position continuation))
      (t
       (let* ((end (%scan-value-end state position))
              (value (cond ((%token-equal-p source position end "true") t)
                           ((%token-equal-p source position end "false") +toml-false+)
                           ((%date-shaped-p source position end)
                            (%parse-date-value state position end))
                           ((%float-token-p source position end)
                            (%parse-float-range state position end))
                           ((%token-equal-p source position end "inf")
                            sb-ext:double-float-positive-infinity)
                           ((%token-equal-p source position end "+inf")
                            sb-ext:double-float-positive-infinity)
                           ((%token-equal-p source position end "-inf")
                            sb-ext:double-float-negative-infinity)
                           ((or (%token-equal-p source position end "nan")
                                (%token-equal-p source position end "+nan")
                                (%token-equal-p source position end "-nan"))
                            +toml-nan+)
                           (t (%parse-integer-range state position end)))))
         (funcall continuation value end))))))

(define-toml-rule toml-read-array (state position)
  (let ((index (1+ position)) (values '()))
    (loop
      (loop
        (setf (toml-reader-state-position state) index)
        (%skip-space-and-comments state)
        (setf index (toml-reader-state-position state))
        (if (member (%source-char state index) '(#\Newline #\Return))
            (progn (%skip-line-ending state)
                   (setf index (toml-reader-state-position state)))
            (return)))
      (when (eql (%source-char state index) #\])
        (return (funcall continuation (coerce (nreverse values) 'simple-vector)
                          (1+ index))))
      (toml-read-value state index
                       (lambda (value next)
                         (push value values)
                         (setf index next)
                         (setf (toml-reader-state-position state) next)
                         (loop
                           (%skip-space-and-comments state)
                           (if (member (%source-char state (toml-reader-state-position state))
                                       '(#\Newline #\Return))
                               (%skip-line-ending state)
                               (return)))
                         (setf index (toml-reader-state-position state))
                         (cond
                           ((eql (%source-char state index) #\,)
                            (incf index))
                           ((not (eql (%source-char state index) #\]))
                            (%error-at state index "comma or closing bracket")))
                         (setf (toml-reader-state-position state) index)
                         (when (eql (%source-char state index) #\])
                           nil))))))

(define-toml-rule toml-read-inline-table (state position)
  (let ((table (make-hash-table :test #'equal)) (index (1+ position)) (created '()))
    (loop
      (setf (toml-reader-state-position state) index)
      (%skip-inline-space state) (setf index (toml-reader-state-position state))
      (when (eql (%source-char state index) #\})
        (setf (gethash table (toml-reader-state-table-states state)) :inline)
        (return (funcall continuation table (1+ index))))
      (multiple-value-bind (keys next) (%read-key-path state index)
        (setf index next)
        (setf (toml-reader-state-position state) index)
        (%skip-inline-space state)
        (setf index (toml-reader-state-position state))
        (unless (eql (%source-char state index) #\=)
          (%error-at state index "="))
        (incf index)
        (setf (toml-reader-state-position state) index)
        (%skip-inline-space state)
        (setf index (toml-reader-state-position state))
        (toml-read-value state index
                         (lambda (value value-end)
                           (let ((target table)
                                 (components (%path-parent keys)))
                             (loop while components
                                   do (multiple-value-bind (key rest)
                                          (%path-next components)
                                        (setf components rest)
                                        (multiple-value-bind (child present)
                                            (gethash key target)
                                        (cond
                                          ((not present)
                                           (setf child (make-hash-table :test #'equal)
                                                 (gethash key target) child
                                                 (gethash child
                                                          (toml-reader-state-table-states state))
                                                 :inline)
                                           (push child created))
                                          ((not (hash-table-p child))
                                           (%error-at state value-end "inline table"))
                                          ((eq (gethash child
                                                        (toml-reader-state-table-states state))
                                               :inline)
                                           (unless (member child created :test #'eq)
                                             (%error-at state value-end "inline table"))))
                                          (setf target child))))
                             (let ((key (%path-last keys)))
                               (when (nth-value 1 (gethash key target))
                                 (%error-at state value-end "unique inline key"))
                               (setf (gethash key target) value)))
                           (setf index value-end
                                 (toml-reader-state-position state) value-end)
                           (%skip-inline-space state)
                           (setf index (toml-reader-state-position state))
                           (cond
                             ((eql (%source-char state index) #\,) (incf index))
                             ((not (eql (%source-char state index) #\}))
                              (%error-at state index "comma or closing brace")))))))))
