;;;; src/reader-document.lisp
(in-package #:cl-toml-kit)

(defun %read-key-component (state position)
  (setf (toml-reader-state-position state) position)
  (%skip-space-and-comments state)
  (setf position (toml-reader-state-position state))
  (let ((char (%source-char state position)))
    (cond
      ((member char '(#\" #\'))
       (when (and (eql (%source-char state (1+ position)) char)
                  (eql (%source-char state (+ position 2)) char))
         (%error-at state position "single-line key"))
       (multiple-value-bind (value next) (%read-string-at state position char)
         (values value next)))
      ((toml-bare-key-character-p char)
       (let ((end (%scan-bare-key-end state position)))
         (values (subseq (toml-reader-state-source state) position end) end)))
      (t (%error-at state position "key")))))

(defun %read-key-path (state position)
  (multiple-value-bind (first-key first-next) (%read-key-component state position)
    (let ((index first-next))
      (setf (toml-reader-state-position state) index)
      (%skip-space-and-comments state)
      (setf index (toml-reader-state-position state))
      (if (not (eql (%source-char state index) #\.))
          (values first-key index)
          (let ((keys (list first-key)))
            (loop
              (incf index)
              (setf (toml-reader-state-position state) index)
              (%skip-space-and-comments state)
              (setf index (toml-reader-state-position state))
              (multiple-value-bind (key next) (%read-key-component state index)
                (push key keys) (setf index next)
                (setf (toml-reader-state-position state) index))
              (%skip-space-and-comments state)
              (setf index (toml-reader-state-position state))
              (unless (eql (%source-char state index) #\.)
                (let ((path (nreverse keys)))
                  (when (and (toml-reader-state-max-depth state)
                             (> (length path) (toml-reader-state-max-depth state)))
                    (%error-at state index "shallower nesting" path))
                  (return (values path index))))))))))

(defun %table-for-path (state path &key (create nil) (dotted nil) base)
  (let ((table (or base (toml-reader-state-root state)))
        (components path))
    (loop while components
          do (multiple-value-bind (key rest) (%path-next components)
               (setf components rest)
               (multiple-value-bind (value present) (gethash key table)
               (cond
                 ((not present)
                  (unless create
                    (%error-at state (toml-reader-state-position state) "defined table" path))
                  (setf value (make-hash-table :test #'equal)
                        (gethash key table) value
                        (gethash value (toml-reader-state-table-states state))
                        (if dotted :dotted :implicit)))
                 ((hash-table-p value)
                  (when (or (eq (gethash value (toml-reader-state-table-states state)) :inline)
                            (and dotted
                                 (eq (gethash value (toml-reader-state-table-states state))
                                     :explicit)))
                    (%error-at state (toml-reader-state-position state) "defined table" path)))
                 ((and (vectorp value) (> (length value) 0)
                       (hash-table-p (aref value (1- (length value)))))
                  (if dotted
                      (%error-at state (toml-reader-state-position state) "table" path)
                      (setf value (aref value (1- (length value))))
                  )
                  (when (eq (gethash value (toml-reader-state-table-states state)) :inline)
                    (%error-at state (toml-reader-state-position state) "inline table" path)))
                 (t (%error-at state (toml-reader-state-position state) "table" path)))
                 (setf table value))))
    table))

(defun %define-assignment (state path value)
  (let* ((base (or (toml-reader-state-current state)
                   (toml-reader-state-root state)))
         (parent (%table-for-path state (%path-parent path) :create t
                                  :dotted (> (%path-length path) 1) :base base))
         (key (%path-last path)))
    (multiple-value-bind (old present) (gethash key parent)
      (declare (ignore old))
      (when present (%error-at state (toml-reader-state-position state) "unique key" path)))
    (setf (gethash key parent) value)
    (when (hash-table-p value)
      (setf (gethash value (toml-reader-state-table-states state)) :inline))))

(defun %read-header (state position array-p)
  (let ((index (+ position (if array-p 2 1))))
    (multiple-value-bind (path next) (%read-key-path state index)
      (setf index next)
      (%skip-space-and-comments state)
      (setf index (toml-reader-state-position state))
      (unless (eql (%source-char state index) #\])
        (%error-at state index "]" path))
      (incf index)
      (when (and array-p (not (eql (%source-char state index) #\])))
        (%error-at state index "]]" path))
      (when array-p (incf index))
      (setf (toml-reader-state-position state) index)
      (%skip-space-and-comments state)
      (unless (member (%source-char state (toml-reader-state-position state))
                      '(nil #\Newline #\Return))
        (%error-at state (toml-reader-state-position state) "line ending" path))
      (let ((parent (%table-for-path state (%path-parent path) :create t))
            (key (%path-last path)))
        (if array-p
            (let ((value (gethash key parent)))
              (when (and value (vectorp value) (zerop (length value)))
                (%error-at state position "array table" path))
              (when (and value (not (vectorp value)))
                (%error-at state position "array table" path))
              (unless value
                (setf value (make-array 0 :adjustable t :fill-pointer 0)
                      (gethash key parent) value))
              (let ((table (make-hash-table :test #'equal)))
                (vector-push-extend table value)
                (setf (gethash table (toml-reader-state-table-states state)) :explicit
                      (gethash (%path-last path) (toml-reader-state-array-tables state)) t)
                (setf (toml-reader-state-current state) table)))
            (let ((table (gethash key parent)))
              (cond
                ((null table)
                 (setf table (make-hash-table :test #'equal)
                       (gethash key parent) table
                       (gethash table (toml-reader-state-table-states state)) :explicit))
                ((not (hash-table-p table)) (%error-at state position "table" path))
                ((member (gethash table (toml-reader-state-table-states state))
                         '(:explicit :dotted))
                 (%error-at state position "unique table" path))
                ((eq (gethash table (toml-reader-state-table-states state)) :inline)
                 (%error-at state position "extendable table" path))
                (t (setf (gethash table (toml-reader-state-table-states state)) :explicit)))
              (setf (toml-reader-state-current state) table))))
      (setf (toml-reader-state-position state) index)
      index)))

(define-toml-rule toml-read-document (state position)
  (let ((index position))
    (loop
      (setf (toml-reader-state-position state) index)
      (%skip-space-and-comments state)
      (setf index (toml-reader-state-position state))
      (cond
        ((>= index (toml-reader-state-length state))
         (return (funcall continuation (toml-reader-state-root state) index)))
        ((member (%source-char state index) '(#\Newline #\Return))
         (%skip-line-ending state) (setf index (toml-reader-state-position state)))
        ((eql (%source-char state index) #\[)
         (let ((array-p (eql (%source-char state (1+ index)) #\[)))
           (setf index (%read-header state index array-p))
           (%skip-line-ending state)
           (setf index (toml-reader-state-position state))))
        (t
         (multiple-value-bind (path next) (%read-key-path state index)
           (setf index next) (%skip-space-and-comments state)
           (unless (eql (%source-char state index) #\=)
             (%error-at state index "=" path))
           (incf index)
           (setf (toml-reader-state-position state) index)
           (%skip-space-and-comments state)
           (setf index (toml-reader-state-position state))
           (toml-read-value state index
                            (lambda (value value-end)
                              (%define-assignment state path value)
                              (setf index value-end)
                              (setf (toml-reader-state-position state) value-end)
                              (%skip-space-and-comments state)
                              (unless
                                  (member (%source-char state
                                                         (toml-reader-state-position state))
                                         '(nil #\Newline #\Return))
                                (%error-at state (toml-reader-state-position state)
                                           "line ending" path))
                              (%skip-line-ending state)
                              (setf index (toml-reader-state-position state))))))))))

(defun %finalize-value (value)
  (cond
    ((and (vectorp value) (adjustable-array-p value))
     (map 'simple-vector #'%finalize-value value))
    ((hash-table-p value)
     (maphash (lambda (key item) (setf (gethash key value) (%finalize-value item))) value)
     value)
    (t value)))
