name: Nix setup
description: Install Nix and configure the project cache.
inputs:
  cachix-cache:
    required: false
    default: ''
  cachix-auth-token:
    required: false
    default: ''
runs:
  using: composite
  steps:
    - uses: DeterminateSystems/nix-installer-action@main
    - uses: cachix/cachix-action@v15
      if: inputs.cachix-cache != ''
      with:
        name: ${{ inputs.cachix-cache }}
        authToken: ${{ inputs.cachix-auth-token }}
